name: Build TensorFlowlite v2.18.0 on Windows debug version
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v2.18.0-debug)'
        required: true
        default: 'v2.18.0-debug'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the TensorFlow repository
      - name: Checkout TensorFlow
        uses: actions/checkout@v4
        with:
          repository: tensorflow/tensorflow
          ref: v2.18.0  # Adjust version as needed

      # Step 2: Verify Chocolatey is available
      - name: Verify Chocolatey Installation
        run: choco --version
        shell: cmd

      # Step 3: Set up MSYS2
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64  # Use 64-bit MinGW environment
          update: true      # Update MSYS2
          install: >        # Install necessary tools
            git
            patch
            unzip
            mingw-w64-x86_64-gcc

      # Step 4: Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 5: Set up Bazelisk
      - name: Set up Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      # Step 6: Install Python dependencies
      - name: Install Python Dependencies
        run: pip install -U six numpy wheel packaging

      # Step 7: Set Python environment variables
      - name: Set Python Paths
        shell: pwsh
        run: |
          $pythonExe = (Get-Command python).Source
          $sitePackages = python -c "import site; print(site.getsitepackages()[0])"
          echo "PYTHON_BIN_PATH=$pythonExe" >> $env:GITHUB_ENV
          echo "PYTHON_LIB_PATH=$sitePackages" >> $env:GITHUB_ENV
          echo "PATH=C:\msys64\mingw64\bin;$env:PATH" >> $env:GITHUB_ENV  # Add MSYS2 to PATH

      # Step 8: Configure TensorFlow
      - name: Configure TensorFlow
        shell: pwsh
        run: |
          $answers = @(
            "${env:PYTHON_BIN_PATH}",  # Q1: Location of Python
            "${env:PYTHON_LIB_PATH}",  # Q2: Python library path
            "N",                       # Q3: ROCm support? No
            "N",                       # Q4: CUDA support? No
            "N",                       # Q5: Use Clang? No (use MSVC)
            "",                        # Q6: Optimization flags (default)
            "N"                        # Q7: Override eigen strong inline? No
          )
          $answers -join "`n" | python configure.py

      # Step 9: Build TensorFlow lite C++
      - name: Build TensorFlow Lite C++ DLL
        run: bazel build //tensorflow/lite:tensorflowlite.dll -c dbg
        shell: cmd

      # Step 10: Build TensorFlow C
      - name: Build TensorFlow Lite C DLL
        run: bazel build //tensorflow/lite/c:tensorflowlite_c.dll -c dbg
        shell: cmd

      # Step 11: Zip
      - name: Zip and Upload Artifact
        run: Compress-Archive -Path bazel-bin\* -DestinationPath tflite_dll_c_cpp.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tflite_dll_c_cpp.zip
          path: tflite_dll_c_cpp.zip

      # Step 12: Create Release and Upload Asset
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass it via env
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v2.18.0 debug
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass it via env
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./tflite_dll_c_cpp.zip
          asset_name: tflite_dll_c_cpp.zip
          asset_content_type: application/zip